services:
  db_sql:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: tfm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tfm_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - tfm_net
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  
  db_server:
    build:
      context: ./db_back
      dockerfile: dockerfile
    container_name: db_server
    ports:
      - "8080:8080"
    networks:      
      - tfm_net
    depends_on:
      - db_sql
      - mongodb
    restart: unless-stopped

  middle_server:
    build:
      context: ./middle_server
      dockerfile: dockerfile
    container_name: middle_server
    ports:
      - "3000:3000"
    networks:      
      - tfm_net
    depends_on:
      - db_server
    restart: unless-stopped
  
  front:
    build:
      context: ./front
      dockerfile: dockerfile
      args: 
        - BACKEND_URL=http://localhost:3000
    container_name: front
    ports:
      - "${FRONTEND_PUBLISH_PORT:-4200}:80"
    networks:
      - tfm_net
    depends_on:
     - middle_server
    restart: unless-stopped
      
  

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  tfm_net:
    driver: bridge