services:
  db_sql:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: tfm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tfm_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - tfm_net
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  
  db_server:
    build:
      context: ./db_back
      dockerfile: dockerfile
    container_name: db_server
    ports:
      - "8080:8080"
    networks:      
      - tfm_net
    depends_on:
      - db_sql
      - mongodb
    restart: unless-stopped

  middle_server:
    build:
      context: ./middle_server
      dockerfile: dockerfile
    container_name: middle_server
    ports:
      - "3000:3000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_AVATARS=avatars
      - MINIO_PUBLIC_BASE_URL=http://localhost:9000/avatars
    networks:      
      - tfm_net
    depends_on:
      - db_server
      - minio
    restart: unless-stopped
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - tfm_net
    restart: unless-stopped

  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/avatars;
      /usr/bin/mc anonymous set public myminio/avatars;
      exit 0;
      "
    networks:
      - tfm_net

  front:
    build:
      context: ./front
      dockerfile: dockerfile
      args: 
        - BACKEND_URL=http://localhost:3000
    container_name: front
    ports:
      - "${FRONTEND_PUBLISH_PORT:-4200}:80"
    networks:
      - tfm_net
    depends_on:
     - middle_server
    restart: unless-stopped
      
  

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  minio_data:
    driver: local

networks:
  tfm_net:
    driver: bridge