services:
  database-sql:
    image: ghcr.io/adriangb46/tfm-database-sql:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tfm_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  database-nosql:
    image: ghcr.io/adriangb46/tfm-database-nosql:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - tfm_net
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  
  db-server:
    image: ghcr.io/adriangb46/tfm-db-server:latest
    container_name: db_server
    environment:
      - DB_HANDSHAKE_SECRET=${DB_HANDSHAKE_SECRET}
      - POSTGRES_URL=jdbc:postgresql://database-sql:5432/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database-nosql:27017/vikingclanwars?authSource=admin
    networks:      
      - tfm_net
    depends_on:
      database-sql:
        condition: service_healthy
      database-nosql:
        condition: service_started
    restart: unless-stopped

  middle-server:
    image: ghcr.io/adriangb46/tfm-middle-server:latest
    container_name: middle_server
    ports:
      - "3000:3000"
    environment:
      - DB_SERVER_URL=http://db-server:8080
      - DB_HANDSHAKE_SECRET=${DB_HANDSHAKE_SECRET}
      - MINIO_ENDPOINT=http://storage-minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_AVATARS=${MINIO_BUCKET_AVATARS}
      - MINIO_PUBLIC_BASE_URL=${MINIO_PUBLIC_BASE_URL}
      - REDIS_URL=redis://cache-redis:6379
    networks:      
      - tfm_net
    depends_on:
      - db-server
      - storage-minio
      - cache-redis
    restart: unless-stopped
  
  cache-redis:
    image: ghcr.io/adriangb46/tfm-cache-redis:latest
    container_name: redis
    networks:
      - tfm_net
    restart: unless-stopped
  
  storage-minio:
    image: ghcr.io/adriangb46/tfm-storage-minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - tfm_net
    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    depends_on:
      - storage-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://storage-minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${MINIO_BUCKET_AVATARS};
      /usr/bin/mc anonymous set public myminio/${MINIO_BUCKET_AVATARS};
      exit 0;
      "
    networks:
      - tfm_net

  frontend:
    image: ghcr.io/adriangb46/tfm-frontend:latest
    container_name: front
    networks:
      - tfm_net
    depends_on:
      - middle-server
    restart: unless-stopped

  nginx-proxy:
    image: ghcr.io/adriangb46/tfm-proxy-nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    networks:
      - tfm_net
    depends_on:
      - frontend
    restart: unless-stopped

  bastion:
    image: ghcr.io/adriangb46/tfm-bastion:latest
    container_name: bastion
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - USER_NAME=${BASTION_USER_NAME}
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=${BASTION_USER_PASSWORD}
    ports:
      - "2222:22"
    networks:
      - tfm_net
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  minio_data:
    driver: local
  letsencrypt_data:
    driver: local
  certbot_data:
    driver: local

networks:
  tfm_net:
    driver: bridge
